#ifndef PARSER_H
#define PARSER_H

#define COMMAND_INVALID 255
#define COMMAND_QSFP_GPIO_READ 0
#define COMMAND_QSFP_GPIO_SET 1
#define COMMAND_QSFP_GPIO_CLEAR 2
#define COMMAND_QSFP_GPIO_TOGGLE 3
#define COMMAND_PEK_GPIO_READ 4
#define COMMAND_PEK_GPIO_SET 5
#define COMMAND_PEK_GPIO_CLEAR 6
#define COMMAND_PEK_GPIO_TOGGLE 7
#define COMMAND_PEK_GPIO_WRITE 8
#define COMMAND_PEK_GPIO_LIST 9
#define COMMAND_ADC_READ 10
#define COMMAND_DAC_WRITE 11
#define COMMAND_SPIXFER 12
#define COMMAND_SPILB 13
#define COMMAND_PEK_IIC_WRITE 14
#define COMMAND_QSFP_IIC_READ 15
#define COMMAND_QSFP_BERT 16
#define COMMAND_QSFP_EYESCAN 17
#define COMMAND_DEBUG_VCU108 18
#define COMMAND_DEBUG_QSFP 19
#define COMMAND_CFP_GPIO_READ 20
#define COMMAND_VCU108_GPIO_READ 21
#define COMMAND_VCU108_GPIO_SET 22
#define COMMAND_VCU108_GPIO_CLEAR 23
#define COMMAND_VCU108_GPIO_TOGGLE 24
#define COMMAND_PEK_IIC_READ 25

// #define ERROR_INVALID_QSFP_PORT 0
#define ERROR_INVALID_PEK_PORT 1
#define ERROR_INVALID_PEK_PIN 2
#define ERROR_INVALID_ADC_CHANNEL 3
#define ERROR_INVALID_GPIO_VALUE 4
#define ERROR_INVALID_EYESCAN_VRANGE 5
#define ERROR_INVALID_EYESCAN_PRESCALE 6
#define ERROR_INVALID_EYESCAN_VMAX 7
#define ERROR_INVALID_EYESCAN_HMAX 8
#define ERROR_INVALID_EYESCAN_DRP 9
#define ERROR_INVALID_EYESCAN_STEPSIZE 10
#define ERROR_INVALID_BERT_PATTERN 11
#define ERROR_INVALID_IIC_WRITE_PAGE 12
#define ERROR_INVALID_PEK_START_ADDRESS 13
#define ERROR_INVALID_PEK_IIC_DATA_TYPE 14
#define ERROR_PEK_WRITE_DATA_TOO_LONG 15
#define ERROR_INVALID_QSFP_IIC_READ_PAGE 16
#define ERROR_INVALID_QSFP_IIC_READ_START_ADDRESS 17
#define ERROR_INVALID_QSFP_IIC_READ_END_ADDRESS 18
#define ERROR_INVALID_PEK_IIC_READ_PAGE 19
#define ERROR_INVALID_PEK_IIC_READ_START_ADDRESS 20
#define ERROR_INVALID_PEK_IIC_READ_END_ADDRESS 21


#define ERROR_OTHER 255

#include "parse_types.h"

command parseCommand(char* commandString);

#endif
