#ifndef PARSER_H
#define PARSER_H

#define COMMAND_INVALID 255
#define COMMAND_PETB_GPIO_READ 0
#define COMMAND_PETB_GPIO_SET 1
#define COMMAND_PETB_GPIO_CLEAR 2
#define COMMAND_PETB_GPIO_TOGGLE 3
#define COMMAND_PEK_GPIO_READ 4
#define COMMAND_PEK_GPIO_SET 5
#define COMMAND_PEK_GPIO_CLEAR 6
#define COMMAND_PEK_GPIO_TOGGLE 7
#define COMMAND_PEK_GPIO_WRITE 8
#define COMMAND_PEK_GPIO_LIST 9
#define COMMAND_ADC_READ 10
#define COMMAND_DAC_WRITE 11
#define COMMAND_SPIXFER 12
#define COMMAND_SPILB 13
#define COMMAND_I2CWRITE 14
#define COMMAND_I2CREAD 15
#define COMMAND_PETB_BERT 16
#define COMMAND_PETB_EYESCAN 17
#define COMMAND_DEBUG_IIC 18
#define COMMAND_DEBUG_GPIO 19

#define ERROR_INVALID_PETB_PORT 0
#define ERROR_INVALID_PEK_PORT 1
#define ERROR_INVALID_PEK_PIN 2
#define ERROR_INVALID_ADC_CHANNEL 3
#define ERROR_INVALID_GPIO_VALUE 4
#define ERROR_INVALID_EYESCAN_VRANGE 5
#define ERROR_INVALID_EYESCAN_PRESCALE 6
#define ERROR_INVALID_EYESCAN_VMAX 7
#define ERROR_INVALID_EYESCAN_HMAX 8
#define ERROR_INVALID_EYESCAN_DRP 9
#define ERROR_INVALID_EYESCAN_STEPSIZE 10
#define ERROR_INVALID_BERT_PATTERN 11


#define ERROR_OTHER 255

#include "parse_types.h"

command parseCommand(char* commandString);

#endif
